[package]
name = "plugin_rust"
version = "0.1.0"
authors = ["urad <ura@jrl.eng.osaka-u.ac.jp>"]
edition = "2018"

# ここのブロックは無くてもうごく
[lib]
name = "mylib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
